micronaut:
  application:
    name: message-command-side
  security:
    enabled: true
    endpoints:
      login:
        enabled: true
      oauth:
        enabled: true
    token:
      jwt:
        enabled: true
        signatures:
          secret:
            generator:
              secret: ${resk.security.secret:pleaseChangeThisSecretForANewOne}
  router:
    versioning:
      enabled: true
      parameter:
        enabled: true
      header:
        enabled: true 
      
postgres:
  reactive:
    client:
      port: 5432
      host: localhost
      database: resk
      user: resk_user
      password: resk_password
      
resk:
  features:
    security-mode: embedded
    discovery-mode: none
    cache-mode: embedded
  routes:
    secured: isAuthenticated()
          
flyway:
  datasources: 
    default: 
      async: true
      locations: classpath:db/migration
      url: 'jdbc:postgresql://${postgres.reactive.client.host}:${postgres.reactive.client.port}/${postgres.reactive.client.database}'
      user: ${postgres.reactive.client.user}
      password: ${postgres.reactive.client.password}

