micronaut:
  application:
    name: message-command-side
  security:
    enabled: true
    endpoints:
      login:
        enabled: true
      oauth:
        enabled: true
    token:
      jwt:
        enabled: true
        signatures:
          secret:
            generator:
              secret: ${resk.security.secret}
  router:
    versioning:
      enabled: true
      default-version: 1
      parameter:
        enabled: true
      header:
        enabled: true 

endpoints:
  health:
    postgres:
      reactive:
        enabled: false

postgres:
  reactive:
    client:
      port: 5432
      host: localhost
      database: resk
      user: resk_user
      password: resk_password
      
resk:
  features:
    storage: memory  # memory, external
    security-mode: embedded # none, embedded, oauth2
    discovery-mode: none # none, external
    cache-mode: embedded # embedded, external
    migration:
      enabled: false
  routes:
    secured: isAuthenticated() # isAnonymous(), isAuthenticated()
  security:
    secret: 3a55132e-5762-451d-95d4-0f72252602ed
          
flyway:
  datasources: 
    default:
      enabled: ${resk.features.migration.enabled}
      async: true
      locations: classpath:db/migration
      url: 'jdbc:postgresql://${postgres.reactive.client.host}:${postgres.reactive.client.port}/${postgres.reactive.client.database}'
      user: ${postgres.reactive.client.user}
      password: ${postgres.reactive.client.password}

