micronaut:
  application:
    name: message-command-side
  security:
    enabled: true
    endpoints:
      login:
        enabled: true
      oauth:
        enabled: true
    token:
      jwt:
        enabled: true
        signatures:
          secret:
            generator:
              secret: pleaseChangeThisSecretForANewOne
  router:
    versioning:
      enabled: true
      parameter:
        enabled: false
      header:
        enabled: true 
      
postgres:
  reactive:
    client:
      port: 5432
      host: localhost
      database: resk
      user: resk_user
      password: resk_password
      
resk:
  version:
    default: 1
  features:
    security-mode: none
    cache-mode: embedded
  routes:
    secured: isAuthenticated()

