version: '3.4'

services: 
  api.gateway:
    image: resk/apigateway:${TAG:-latest}
    container_name: apigateway
    ports:
      - '8080:80'
    environment: 
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ASPNETCORE_ENVIRONMENT=Production
      - GlobalConfiguration__BaseUrl
    depends_on: 
      - command.side
  command.side:
    image: resk/command-api:${TAG:-latest}
    container_name: command
